//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_NguyenVanQuyet_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thanh_Toan
    {
        public int id_thanh_toan { get; set; }
        public Nullable<int> id_don_hang { get; set; }
        public Nullable<System.DateTime> ngay_thanh_toan { get; set; }
        public decimal so_tien { get; set; }
        public string phuong_thuc { get; set; }
    
        public virtual Don_Hang Don_Hang { get; set; }
    }
}
