//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_NguyenVanQuyet_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yeu_Thich
    {
        public int id_yeu_thich { get; set; }
        public Nullable<int> id_nguoi_dung { get; set; }
        public Nullable<int> id_san_pham { get; set; }
        public Nullable<System.DateTime> ngay_them { get; set; }
    
        public virtual Nguoi_Dung Nguoi_Dung { get; set; }
        public virtual San_Pham San_Pham { get; set; }
    }
}
